spring:
  application:
    name: SpringDemo
  main:
    allow-bean-definition-overriding: true
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
  error:
    include-message: always

db:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:spring-demo
    username: root
    password: root
    maxLifetime: 420000
    idleTimeout: 60000
    maximumPoolSize: 10
    leakDetectionThreshold: 0
    prepStmtCacheSize: 250
    cachePrepStmts: true
    cacheServerConfiguration: true
    connectionTimeout: 30000
    minimumIdle: 5